version: '3'
services:

  redis:
      image: redis

  web:
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    build:
      context: ./web/
    ports:
      - "5000:5000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web

